### ISSUE TITLE
Undefined offset: 5 in Html2Pdf.php on line 5099

### ISSUE THREAD

**Issue by divinity76** [spipu/html2pdf#196]
trying to render the html below uses over 120 seconds, and finally ends in
```
 Notice: Undefined offset: 5 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Notice: Undefined offset: 5 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Notice: Undefined offset: 5 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Notice: Undefined offset: 5 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Fatal error: Uncaught Exception: TCPDF ERROR: Some data has already been output, can't send PDF file in /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: #0 /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php(7620): TCPDF->Error('Some data has a...') #1 /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php(515): TCPDF->Output('exemple07.pdf', 'I') #2 /home/hanshenrik/projects/sales2/pdf_generator.php(22): Spipu\Html2Pdf\Html2Pdf->Output('exemple07.pdf') #3 {main} thrown in /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927
```
versions: PHP-fpm 7.0.19-1, nginx/1.10.3, html2pdf dev-master revision 54d2c21df2e580ad1857d9c2f7b279e103c0dee2

code i used to render: 
(PS:i KNOW this code is vulnerable to information disclousure by sending `?layout=../../../../../../../etc/passwd\x00` - this is on a private development environment, it will be fixed before it enters production, no need to point that out.)
```
<?php
declare(strict_types = 1);
require_once ('vendor/autoload.php');

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

try {
	// get the HTML
	ob_start ();
	require 'pdfgenerator_internals/res/invoicelayout' . $_GET ['layout'] . '.php';
	$content = ob_get_clean ();
	if (! empty ( $_GET ['html'] )) {
		echo $content;
		return;
	}
	$html2pdf = new Html2Pdf ( 'P', 'A4', 'en' );
	$html2pdf->pdf->SetDisplayMode ( 'fullwidth' );
	$html2pdf->writeHTML ( $content );
	// $html2pdf->previewHTML ( $content ) & die ();
	$html2pdf->Output ( 'exemple07.pdf' );
} catch ( Html2PdfException $e ) {
	$formatter = new ExceptionFormatter ( $e );
	echo $formatter->getHtmlMessage ();
}
```

- html: 
```
<page backcolor="#FEFEFE" backimg="./pdfgenerator_internals/res/bas_page.png" backimgx="center" backimgy="bottom" backimgw="100%" backtop="0" backbottom="30mm" footer="date;heure;page" style="font-size: 12pt">

<div><img src="./pdfgenerator_internals/res/logo.gif" style="width:100px;height:100px;" /><br/>
<pre>Honning AS 
Postbox 3,
3109, Tønsberg
Norway</pre></div>
<div style="position: absolute;left:300px;top:0px;/*font-weight:bold;*/font-size:big;text-align: center;"><pre>
FAKTURA
Fakuranr: <span id="invoice_id">$FAKTURANR$</span>
Fakutadato: <span id="invoice_date">$FAKTURADATO$</span>
Kundenr: <span id="customer_id">$KUNDENR$</span>
KIDnr: <span id="kindnr">$KIDNR$</span>
</pre>
</div>
<div style="position:absolute;left:390px;top:170px;"><pre>MVA Foretaksregister: <span id="our_orgnr">$OUR_ORGNR$</span></pre></div>


<div style="position:absolute;left:390px;top:180px;"><pre>
Betales Innen: <span id="due_date">$DUE_DATE$</span>
Betalings Betingelser: 
<span id="payment_terms">$PAYMENT_TERMS$</span>
</pre></div>

<div><pre>
Deres ref: <span id="customer_ref">$CUSTOMER_REF$</span>
Vår ref: <span id="our_ref">$OUR_REF$</span>
</pre></div>
<br/><br/>
<div style="border-collapse: collapse;border: solid thin;"><pre id="insert_items_here">
<table class="sortable">
	<thead>
		<tr>
<th>DNB XML faktura</th>
<th>rediger</th>
<th>id</th>
<th>order_id</th>
<th>pmtTermsText</th>
<th>creation_date</th>
<th>due_date</th>
<th>interestRate</th>
<th>paid</th>
<th>misc</th>
		</tr>
	</thead>
	<tbody>
<tr style="text-align:center;">
<td ><span><a href="dnbxml_generator.php?invoiceID=1">trykk for DNB XML</a></span></td>
<td ><span><a href="edit_existing_row.php?table=invoices&amp;id=1"><img class="editButton" src="https://honningas.no/phpmyadmin/themes/pmahomme/img/b_edit.png" /></a></span></td>
<td ><span>1</span></td>
<td ><span>1</span></td>
<td ><span>test</span></td>
<td ><span>2017-06-01</span></td>
<td ><span>2019-12-20</span></td>
<td ><span>0.00</span></td>
<td ><span>0.00</span></td>
<td ><span>test</span></td>
</tr>
<tr style="text-align:center;">
<td ><span><a href="dnbxml_generator.php?invoiceID=4000">trykk for DNB XML</a></span></td>
<td ><span><a href="edit_existing_row.php?table=invoices&amp;id=4000"><img class="editButton" src="https://honningas.no/phpmyadmin/themes/pmahomme/img/b_edit.png" /></a></span></td>
<td ><span>4000</span></td>
<td ><span>4000</span></td>
<td ><span>testt</span></td>
<td ><span>2017-01-06</span></td>
<td ><span>2017-02-27</span></td>
<td ><span>0.00</span></td>
<td ><span>999.00</span></td>
<td ><span>test</span></td>
</tr>
<tr style="text-align:center;">
<td ><span><a href="dnbxml_generator.php?invoiceID=4001">trykk for DNB XML</a></span></td>
<td ><span><a href="edit_existing_row.php?table=invoices&amp;id=4001"><img class="editButton" src="https://honningas.no/phpmyadmin/themes/pmahomme/img/b_edit.png" /></a></span></td>
<td ><span>4001</span></td>
<td ><span>4016</span></td>
<td ><span>test</span></td>
<td ><span>2017-09-19</span></td>
<td ><span>2017-02-19</span></td>
<td ><span>0.00</span></td>
<td ><span>99.00</span></td>
<td ><span>test</span></td>
</tr>
<tr style="text-align:center;">
<td ><span><a href="dnbxml_generator.php?invoiceID=4002">trykk for DNB XML</a></span></td>
<td ><span><a href="edit_existing_row.php?table=invoices&amp;id=4002"><img class="editButton" src="https://honningas.no/phpmyadmin/themes/pmahomme/img/b_edit.png" /></a></span></td>
<td ><span>4002</span></td>
<td ><span>4018</span></td>
<td ><span>30 dager</span></td>
<td ><span>2017-06-07</span></td>
<td ><span>2017-07-07</span></td>
<td ><span>1.50</span></td>
<td ><span>0.00</span></td>
<td ><span>null</span></td>
</tr>
	</tbody>
	<tfoot>
		<!--  		<tr>
			<td>TOTAL</td>
			<td>45,000</td>
		</tr>
		-->
	</tfoot>
</table>
</pre></div>
</page>

```

**Comment by divinity76** [comment]
and with this html, i get

```
 Notice: Undefined offset: 4 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Notice: Undefined offset: 4 in /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5099

Fatal error: Uncaught Exception: TCPDF ERROR: Some data has already been output, can't send PDF file in /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: #0 /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php(7620): TCPDF->Error('Some data has a...') #1 /home/hanshenrik/projects/sales2/vendor/spipu/html2pdf/src/Html2Pdf.php(515): TCPDF->Output('exemple07.pdf', 'I') #2 /home/hanshenrik/projects/sales2/pdf_generator.php(23): Spipu\Html2Pdf\Html2Pdf->Output('exemple07.pdf') #3 {main} thrown in /home/hanshenrik/projects/sales2/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927
```

```html
<page backcolor="#FEFEFE" backimg="./pdfgenerator_internals/res/bas_page.png" backimgx="center" backimgy="bottom" backimgw="100%" backtop="0" backbottom="30mm" footer="date;heure;page" style="font-size: 12pt">

<div><img src="./pdfgenerator_internals/res/logo.gif" style="width:100px;height:100px;" /><br/>
<pre>Honning AS 
Postbox 3,
3109, Tønsberg
Norway</pre></div>
<div style="position: absolute;left:300px;top:0px;/*font-weight:bold;*/font-size:big;text-align: center;"><pre>
FAKTURA
Fakuranr: <span id="invoice_id">$FAKTURANR$</span>
Fakutadato: <span id="invoice_date">$FAKTURADATO$</span>
Kundenr: <span id="customer_id">$KUNDENR$</span>
KIDnr: <span id="kindnr">$KIDNR$</span>
</pre>
</div>
<div style="position:absolute;left:390px;top:170px;"><pre>MVA Foretaksregister: <span id="our_orgnr">$OUR_ORGNR$</span></pre></div>


<div style="position:absolute;left:390px;top:180px;"><pre>
Betales Innen: <span id="due_date">$DUE_DATE$</span>
Betalings Betingelser: 
<span id="payment_terms">$PAYMENT_TERMS$</span>
</pre></div>

<div><pre>
Deres ref: <span id="customer_ref">$CUSTOMER_REF$</span>
Vår ref: <span id="our_ref">$OUR_REF$</span>
</pre></div>
<br/><br/>
<div style="border-collapse: collapse;border: solid thin;">
<table class="sortable">
	<thead>
		<tr>
<th>rediger</th>
<th>id</th>
<th>name</th>
<th>misc</th>
		</tr>
	</thead>
	<tbody>
<tr style="text-align:center;">
<td ><span></span></td>
<td ><span>1</span></td>
<td ><span>uidentifisert</span></td>
<td ><span>test</span></td>
</tr>
<tr style="text-align:center;">
<td ><span></span></td>
<td ><span>2</span></td>
<td ><span>Cecilie Hyllseth</span></td>
<td ><span></span></td>
</tr>
<tr style="text-align:center;">
<td ><span></span></td>
<td ><span>3</span></td>
<td ><span>Bent Kittelsen</span></td>
<td ><span>Daglig leder</span></td>
</tr>
	</tbody>
	<tfoot>
		<!--  		<tr>
			<td>TOTAL</td>
			<td>45,000</td>
		</tr>
		-->
	</tfoot>
</table>
</div>
</page>
```

**Comment by divinity76** [comment]
i have tracked it down to being a problem with the <tfoot> tag...

**Comment by divinity76** [comment]
`<table><tfoot></tfoot></table>` triggers the error.

`<table><tfoot><tr></tr></tfoot></table>`
does not trigger the error.

a quickfix: 
add 
`if(!empty(self::$_tables[$param['num']]['cases'][$tr]))` to https://github.com/spipu/html2pdf/blob/54d2c21df2e580ad1857d9c2f7b279e103c0dee2/src/Html2Pdf.php#L5099  line 5099

**Comment by spipu** [comment]
you are right, i did not put a test if the tfoot (or thead, or tbody) was empty... why  putting a useles tag ?

You must have at least one TR in a thead ot tfoot tag.

**Comment by divinity76** [comment]
Not according to the specs, you don't. Quote ```Content model:
Zero or more tr and script-supporting elements``` -- https://www.w3.org/TR/html5/tabular-data.html#the-tfoot-element

**Comment by spipu** [comment]
maybe, but it will be slower for html2pdf if you put useless tags.

**Comment by spipu** [comment]
protection added : https://github.com/spipu/html2pdf/commit/dd9262e4b7a8658bfecf50cf2685536eb3f25d76

**Comment by divinity76** [comment]
just for the record, instead of fixing the bug and becoming specs compliant, which would have taken 1 line of code, you opted to add tests to make sure that you are explicitly NOT specs compliant, with 133 new lines of code specifically for that purpose.

brilliant!
