### ISSUE TITLE
Asked Tag [polygon ] is not in the [Draw] tag ....

### ISSUE THREAD

**Issue by imranctg16** [spipu/html2pdf#442]
I am getting this error when my html has this ->
`<draw width="16" height="10">
            <polygon points="5,0 10,8 0,8"/>
        </draw>`   i checked the vendor file,, and the polygon.php file is there.. what could be the reason for this error ?

**Comment by imranctg16** [comment]
More Detailed Error Message : `Spipu\Html2Pdf\Exception\HtmlParsingException: The asked [polygon] tag is not in a [DRAW] tag in /vendor/spipu/html2pdf/src/Tag/AbstractSvgTag.php:68 Stack trace: #0 /vendor/spipu/html2pdf/src/Tag/AbstractSvgTag.php(45): Spipu\Html2Pdf\Tag\AbstractSvgTag->openSvg(Array) #1 /vendor/spipu/html2pdf/src/Html2Pdf.php(1436): Spipu\Html2Pdf\Tag\AbstractSvgTag->open(Array) #2 /vendor/spipu/html2pdf/src/Html2Pdf.php(1407): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node)) #3 /vendor/spipu/html2pdf/src/Html2Pdf.php(5583): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode() #4 /vendor/spipu/html2pdf/src/Html2Pdf.php(1439): Spipu\Html2Pdf\Html2Pdf->_tag_open_TD(Array) #5 /vendor/spipu/html2pdf/src/Html2Pdf.php(1393): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node)) #6 /vendor/spipu/html2pdf/src/Html2Pdf.php(595): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode() #7 /home/bs166/Downloads/kaizen/app/Traits/PdfGeneratorTraits.php(31): Spipu\Html2Pdf\Html2Pdf->writeHTML('\n ...') #8 /app/Http/Controllers/DetailController.php(116): App\Http\Controllers\DetailController->generatePdf('`

**Comment by LittleBigFox** [comment]
Hi!

Yes it's strange, because Html2PDF allow this svg tag... https://github.com/spipu/html2pdf/blob/master/examples/res/svg.php

I take a look on this, but i'm not an expert of svg...

Regards,
LBF

**Comment by LittleBigFox** [comment]
I tried the polygon tag, it work... Could you provide the full draw tag please?

Regards,
LBF

**Comment by imranctg16** [comment]
Sure . 
`<draw width="16" height="10">
            <polygon points="5,0 10,8 0,8"/>
</draw>`
My PHP version: 7.2.14
Laravel version: 5.6.39
spipu/html2pdf   v5.2.1

**Comment by LittleBigFox** [comment]
Ok, i try you code, and it work... I guess there is another problem here...
Are you sure you have nothing more than this line `<draw>...</draw>` ?

`The asked [polygon] tag is not in a [DRAW] tag in /vendor/spipu/html2pdf/src/Tag/AbstractSvgTag.php:68`
Suggests that the tag is corrupt.

**Comment by imranctg16** [comment]
if i only use the draw tag,, it works fine.. but when i put it under div tag,, it shows that error .
`   <draw width="16" height="10">
        <polygon points="5,0 10,8 0,8"/>
    </draw>
` This works Just fine. But when it is nested under a div tag, it shows error

**Comment by spipu** [comment]
it may be a bug :( i tag it !

**Comment by dbazza** [comment]
In AbstractSvgTag.php, I've commented this method like this:

protected function openSvg($properties)
    {
        /* if (!$this->svgDrawer->isDrawing()) {
            $e = new HtmlParsingException('The asked ['.$this->getName().'] tag is not in a [DRAW] tag');
            $e->setInvalidTag($this->getName());
            throw $e;
        } */

        ...

This is a workaround working for me...

**Comment by WideeFr** [comment]
I have the same problem with V5.2.2 on php 7.4
If i commented like dbazza, the script doesn't generate de svg
i tried with the example, and it doesn't works anymore

**Comment by hamzahfauzy** [comment]
is there any update ??

**Comment by RobinBrackez** [comment]
I get the same error with <path> inside <draw>

"The asked [path] tag is not in a [DRAW] tag"
