### ISSUE TITLE
Fatal error: Uncaught Exception: TCPDF ERROR: Could not include font definition 

### ISSUE THREAD

**Issue by yourchoice** [spipu/html2pdf#586]
Fatal error: Uncaught Exception: TCPDF ERROR: Could not include font definition file: yanone kaffeesatz in ..\vendor\tecnickcom\tcpdf\tcpdf.php:2950 Stack trace: #0 ..\vendor\tecnickcom\tcpdf\tcpdf.php(4298): TCPDF->Error('Could not inclu...') #1 ..\vendor\tecnickcom\tcpdf\tcpdf.php(4459): TCPDF->AddFont('yanone kaffeesa...', '', '', true) #2 ..\vendor\spipu\html2pdf\src\Parsing\Css.php(371): TCPDF->SetFont('yanone kaffeesa...', '', 21) #3 ..\vendor\spipu\html2pdf\src\Html2Pdf.php(4094): Spipu\Html2Pdf\Parsing\Css->fontSet() #4 ..\vendor\spipu\html2pdf\src\Html2Pdf.php(1439): Spipu\Html2Pdf\Html2Pdf->_tag_open_H1(Array) #5 ..\vendor\spipu\html2pdf\src\Html2Pdf.php(1407): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node)) #6 ..\vendor\spipu\html2pdf\src\Html2Pdf in ..\vendor\tecnickcom\tcpdf\tcpdf.php on line 2950

**Comment by a4992214** [comment]
I have just installed this (using composer & php8.2) to test it but get the same problem...

`Fatal error: Uncaught Exception: TCPDF ERROR: Could not include font definition file: ..... \vendor\tecnickcom\tcpdf\tcpdf.php on line 3006`
