### ISSUE TITLE
Fatal error: Uncaught Spipu\Html2Pdf\Exception\HtmlParsingException: Tags are closed in a wrong order for [div] 

### ISSUE THREAD

**Issue by sugamkarki** [spipu/html2pdf#652]
```
Fatal error: Uncaught Spipu\Html2Pdf\Exception\HtmlParsingException: Tags are closed in a wrong order for [div] in D:\NAMI\Year 2\Term II\Assignments\Group Project\GroupProject\vendor\spipu\html2pdf\src\Parsing\Html.php:262 Stack trace: #0 D:\NAMI\Year 2\Term II\Assignments\Group Project\GroupProject\vendor\spipu\html2pdf\src\Parsing\Html.php(94): Spipu\Html2Pdf\Parsing\Html->getTagAction(Object(Spipu\Html2Pdf\Parsing\Token), Array) #1 D:\NAMI\Year 2\Term II\Assignments\Group Project\GroupProject\vendor\spipu\html2pdf\src\Html2Pdf.php(594): Spipu\Html2Pdf\Parsing\Html->parse(Array) #2 D:\NAMI\Year 2\Term II\Assignments\Group Project\GroupProject\index.php(947): Spipu\Html2Pdf\Html2Pdf->writeHTML('\r\n\r\n<section st...') #3 {main} thrown in D:\NAMI\Year 2\Term II\Assignments\Group Project\GroupProject\vendor\spipu\html2pdf\src\Parsing\Html.php on line 262
```

**Comment by W0rma** [comment]
@sugamkarki I'm afraid it's hard to help here without knowing your code which caused the mentioned error.

Would you mind sharing it here?

Which version of `spipu/html2pdf` are you using?
