### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by OscarAlegui** [spipu/html2pdf#672]
Hi, I need help I have this error. anyone can help me ! thanks in advance

`Fatal error: Uncaught Spipu\Html2Pdf\Exception\TableException: The content of the TD tag does not fit on only one page in /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/vendor/spipu/html2pdf/src/Html2Pdf.php:5668 Stack trace: #0 /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/vendor/spipu/html2pdf/src/Html2Pdf.php(1439): Spipu\Html2Pdf\Html2Pdf->_tag_close_TD(Array) #1 /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/vendor/spipu/html2pdf/src/Html2Pdf.php(1393): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node)) #2 /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/vendor/spipu/html2pdf/src/Html2Pdf.php(595): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode() #3 /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/index.php(23): Spipu\Html2Pdf\Html2Pdf->writeHTML('\n <page>\n<!-...') #4 {main} thrown in /home/xlikqebq/public_html/meatlovers/sistema/booking/admin/pdf/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5668`

And this is my HTML code in this [webpage](https://inetlab.cl/meatlovers/sistema/booking/admin/pdf/pruebacotizacion.html)

`<html>
<head>
<title>Untitled-1</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<table id="Table_01" width="594" height="2544" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="8">
			<img src="images/pruebacotizacion_01.jpg" width="260" height="63" alt=""></td>
		<td rowspan="24">
			<img src="images/pruebacotizacion_02.jpg" width="334" height="846" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" rowspan="2">
			<img src="images/pruebacotizacion_03.jpg" width="46" height="479" alt=""></td>
		<td colspan="3">
			<img src="images/pruebacotizacion_04.jpg" width="163" height="134" alt=""></td>
		<td colspan="3" rowspan="2">
			<img src="images/pruebacotizacion_05.jpg" width="51" height="479" alt=""></td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="images/pruebacotizacion_06.jpg" width="163" height="345" alt=""></td>
	</tr>
	<tr>
		<td rowspan="21">
			<img src="images/pruebacotizacion_07.jpg" width="25" height="304" alt=""></td>
		<td colspan="6">
			<img src="images/pruebacotizacion_08.jpg" width="210" height="10" alt=""></td>
		<td rowspan="21">
			<img src="images/pruebacotizacion_09.jpg" width="25" height="304" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_10.jpg" width="210" height="50" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_11.jpg" width="210" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_12.jpg" width="210" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_13.jpg" width="210" height="7" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_14.jpg" width="210" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_15.jpg" width="210" height="6" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_16.jpg" width="210" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_17.jpg" width="210" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_18.jpg" width="210" height="19" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_19.jpg" width="210" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_20.jpg" width="210" height="9" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_21.jpg" width="210" height="5" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_22.jpg" width="210" height="16" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_23.jpg" width="210" height="4" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_24.jpg" width="210" height="11" alt=""></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="images/pruebacotizacion_25.jpg" width="210" height="14" alt=""></td>
	</tr>
	<tr>
		<td colspan="5">
			<img src="images/pruebacotizacion_26.jpg" width="206" height="63" alt=""></td>
		<td rowspan="4">
			<img src="images/pruebacotizacion_27.jpg" width="4" height="110" alt=""></td>
	</tr>
	<tr>
		<td colspan="5">
			<img src="images/pruebacotizacion_28.jpg" width="206" height="16" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="images/pruebacotizacion_29.jpg" width="65" height="11" alt=""></td>
		<td rowspan="2">
			<img src="images/pruebacotizacion_30.jpg" width="79" height="31" alt=""></td>
		<td colspan="2">
			<img src="images/pruebacotizacion_31.jpg" width="62" height="11" alt=""></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="images/pruebacotizacion_32.jpg" width="65" height="20" alt=""></td>
		<td colspan="2">
			<img src="images/pruebacotizacion_33.jpg" width="62" height="20" alt=""></td>
	</tr>
	<tr>
		<td colspan="8">
			<img src="images/pruebacotizacion_34.jpg" width="260" height="847" alt=""></td>
		<td rowspan="2">
			<img src="images/pruebacotizacion_35.jpg" width="334" height="1697" alt=""></td>
	</tr>
	<tr>
		<td colspan="8">
			<img src="images/pruebacotizacion_36.jpg" width="260" height="850" alt=""></td>
	</tr>
	<tr>
		<td>
			<img src="images/spacer.gif" width="25" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="21" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="44" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="79" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="40" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="22" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="4" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="25" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="334" height="1" alt=""></td>
	</tr>
</table>

</body>
</html>`

**Comment by GeoffreyOlivier** [comment]
Read the problem !
